SuperB_Wolves/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from product.views import Productview


from SuperB_Wolves.settings import STATICFILES_DIRS
from rest_framework_simplejwt.views import TokenVerifyView
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)

urlpatterns = [
    path('admin/', admin.site.urls),
    #path('social-auth/', include('social.apps.django_app.urls', namespace='social')),
    path('', include('blog.urls')),
    path('', include('core.urls')),
    path('', include('order.urls')),
    path('', include('product.urls')),
    path('', include('user.urls')),
    path('social-auth/', include('social_django.urls', namespace='social')),
    path('API/', include('product.API.urls')),
    path('API/', include('order.API.urls')),
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('api/token/verify/', TokenVerifyView.as_view(), name='token_verify'),

]
from django.conf.urls.static import static
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL , document_root = settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path, include
from .views import PostListView, PostDetail


urlpatterns = [
    # path('admin/', admin.site.urls),
    path('blog/', PostListView.as_view(), name='blog'),
    path('blog_detail/<slug:slug>/', PostDetail.as_view(), name='blog_detail'),
    path('hitcount/', include(('hitcount.urls', 'hitcount'), namespace='hitcount')),
]

user/urls.py
from django.urls import path,include

from django.contrib.auth import views as auth_views #import this
from django.contrib.auth.views import LogoutView
from .views import account_informatin,address_book,change_password,login_view,RegisterView, activate,LogInView,ResetPasswordView, ResetPasswordConfirmView
urlpatterns = [
   
    path('account_information/', account_informatin, name='account_information'),
    path('address_book/', address_book,name='address_book'),
    path('change_password/', change_password, name= 'change_password'),
    path('login/', login_view, name='login'),
    path('register/', RegisterView.as_view(), name='register'),
    path('login/', LogInView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'), #yoxla logout.html

    #path('password_reset_done/',password_reset_done,name='password_reset_done'),
    # path('password_reset_confirm/<str:uidb64>/<str:token>/',
    #     ResetPasswordConfirmView.as_view(),
    #     name='password_reset_confirm'),
    #path('password_reset_complete/',PasswordResetCompleteView.as_view(template_name='password_reset_complete.html'),name='password_reset_complete'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='password_reset_done.html'), name='password_reset_done'),
    path('password_reset_confirm/<str:uidb64>/<str:token>/', auth_views.PasswordResetConfirmView.as_view(template_name="password_reset_confirm.html"), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='password_reset_complete.html'), name='password_reset_complete'), 
    path("password_reset", ResetPasswordView.as_view(), name="password_reset"),
    path('confirmation/<str:uidb64>/<str:token>/', activate ,name='confirmation'),

]

user/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    image = models.ImageField(upload_to="User_Profile")
    
    def __str__(self):
        return self.username 

    class Meta:
        verbose_name = "User"
        verbose_name_plural = "Users"

class Account_Information(models.Model):
    first_name=models.CharField(max_length=100, blank=False)
    last_name=models.CharField(max_length=100, blank=False)
    email=models.EmailField(max_length=100, blank=False, unique=True)
    created_at=models.DateField(auto_now_add=True)
    updated_at=models.DateField(auto_now=True)

    def __str__(self):
        return self.first_name

class ShippingAddress(models.Model):
    name = models.CharField(max_length=1024 )
    company = models.CharField(max_length=1024 ) 
    city = models.CharField(max_length=1024)
    address1 = models.CharField(max_length=1024)
    address2 = models.CharField(max_length=1024 )
    country = models.CharField(max_length=30)
    zip_code = models.CharField(max_length=12)
    created_at=models.DateField(auto_now_add=True)
    updated_at=models.DateField(auto_now=True)
    
    def __str__(self):
        return self.name

class Forgot_password(models.Model):
   email=models.EmailField(max_length=100, blank=False, unique=True)
   
   def __str__(self):
        return self.email

class Reset_password(models.Model):
   new_password1 = models.CharField(max_length=32)
   new_password2 = models.CharField(max_length=32)
   
   def __str__(self):
        return self.new_password1

user/forms.py
from urllib import request
from django import forms
from django.contrib.auth.forms import (UserCreationForm, 
AuthenticationForm, PasswordResetForm ,SetPasswordForm,PasswordChangeForm,UsernameField)
from django.contrib.auth import get_user_model
from .models import Account_Information,ShippingAddress,Forgot_password,User

class UserRegisterForm(UserCreationForm):

    password1 = forms.CharField(label="Password", widget=forms.PasswordInput(attrs={'class': 'input-text', 'placeholder': 'Your Password'}))

    password2 = forms.CharField(label="Confirm Password", widget=forms.PasswordInput(attrs={'class': 'input-text', 'placeholder': 'Your Confirm Password'}))
                                                            
    class Meta:
        model = get_user_model()
        fields = ['first_name', 'last_name', 'username', 'email', 'password1', 'password2']
        
        widgets = {
            'first_name': forms.TextInput(attrs={'class': 'input-text',
                                                'placeholder': "Your First Name"}),
            'last_name': forms.TextInput(attrs={'class': 'input-text',
                                                'placeholder': "Your Last Name"}),
            'email': forms.EmailInput(attrs={'class': 'input-text',
                                            'placeholder': "Your Email Address"}),
            'username': forms.TextInput(attrs={'class': 'input-text',
                                                'placeholder': "Your Username"})
        }

class LoginForm(AuthenticationForm):  # type: ignore

    username: UsernameField(widget=forms.TextInput(attrs={'class': 'form-control',
                                                'placeholder': "Your Username"}))  # type: ignore
    password: forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control',
                                                'placeholder': "Your Password"}))  # type: ignore
        


    def clean_password2(self):
        password1 = self.cleaned_data["password1"]
        password2 = self.cleaned_data["password2"]

        if password1 != password2:
            raise forms.ValidationError("Password and confirm password doesn't match")
        return password2


class LoginForm(forms.Form):
    username= forms.CharField(widget=forms.TextInput(attrs={
        "class": "form-control ",
        "placeholder": "Username"
    }))

    password =forms.CharField(widget=forms.PasswordInput(attrs={
        "class": "form-control ",
        "placeholder": "Password"
    }))

class ResetPasswordForm(PasswordResetForm):
    email = forms.EmailField(label="Email Address", 
        widget=forms.EmailInput(
            attrs={
                'class': 'form-control',
                'placeholder': 'Email Address'
            }))


class CustomSetPasswordForm(SetPasswordForm):
    new_password1 = forms.CharField(required=True, label='New Password',
        widget=forms.PasswordInput(
            attrs={
                'class': 'form-control',
                'placeholder': 'Your New Password'
            }))
    new_password2 = forms.CharField(required=True, label='Confirm New Password',
        widget=forms.PasswordInput(
            attrs={
                'class': 'form-control',
                'placeholder': 'Confirm Your New Password'
            }))

class ChangePasswordForm(PasswordChangeForm):
    old_password = forms.CharField(required=True, label='Old Password',
        widget=forms.PasswordInput(
            attrs={
                'class': 'form-control',
                'placeholder': 'Your Old Password'
            }))
    new_password1 = forms.CharField(required=True, label='New Password',
        widget=forms.PasswordInput(
            attrs={
                'class': 'form-control',
                'placeholder': 'Your New Password'
            }))
    new_password2 = forms.CharField(required=True, label='Confirm New Password',
        widget=forms.PasswordInput(
            attrs={
                'class': 'form-control',
                'placeholder': 'Confirm Your New Password'
            }))


class Account_InformationForm(forms.ModelForm):
    class Meta:
        model = Account_Information
        fields='__all__'
        
        widgets={
            "first_name": forms.TextInput(
                attrs={
                    'class':"form-control",
                    'placeholder':"First name"
                }
            ),
            "last_name": forms.TextInput(
                attrs={
                    'class':"form-control",
                    'placeholder': "Last name"
                }
            )
        }


class ShippingAddressForm(forms.ModelForm):
    class Meta:
        model = ShippingAddress
        fields= '__all__'


class Forgot_passwordForm(forms.ModelForm):
    class Meta:
        model = Forgot_password
        fields='__all__'
        
        widgets={
            "email": forms.EmailInput(
                attrs={
                    'class':"form-control",
                    'placeholder':"Email"
                }
            ),
        }

user/views.py
from .models import *
from .forms import UserRegisterForm, LoginForm,ResetPasswordForm,CustomSetPasswordForm, ChangePasswordForm
from django.contrib.auth.views import LoginView, PasswordResetView, PasswordResetConfirmView
from django.utils.encoding import force_bytes,force_str
from django.contrib import messages #import messages
from django.template.loader import render_to_string
from django.utils.http import urlsafe_base64_encode
from django.utils.http import urlsafe_base64_decode
from django.contrib.sites.shortcuts import get_current_site
from django.core.mail import send_mail, BadHeaderError
from .tokens import account_activation_token

from django.contrib.auth.views import LoginView, PasswordResetView

from django.shortcuts import render,redirect
from .forms import UserRegisterForm,LoginForm ,Account_InformationForm
from django.contrib.auth import authenticate,login
from django.urls import reverse_lazy
from django.views.generic import CreateView
from .models import User
from SuperB_Wolves.settings import EMAIL_HOST_USER


class RegisterView(CreateView):
    template_name='register.html'
    form_class=UserRegisterForm
    success_url=reverse_lazy('login')

    def post(self,request,*args,**kwargs):
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            User = form.save(commit=False)
            User.is_active = False
            User.save()

            subject = "Activate Your Account"
            current_site = get_current_site(request)
            messages = render_to_string("confirmation_email.html",{
                "User" : User ,
                "domain": current_site.domain,
                "uid" : urlsafe_base64_encode(force_bytes(User.pk)),
                "token" : account_activation_token.make_token(User)

            })

            from_email = EMAIL_HOST_USER
            to_email = request.POST['email']
            send_mail(subject,messages,from_email,[to_email, ])

            return(redirect("/"))
        return render(request, self.template_name, {'form': form})

class LogInView(LoginView):
    template_name = 'login.html'
    form_class = LoginForm

class ResetPasswordView(PasswordResetView):
    template_name = 'password_reset.html'
    form_class = ResetPasswordForm
    email_template_name= 'password_reset_email.html'
    subject_template_name = 'reset_password_subject.txt'
    success_message = "We've emailed you instructions for setting your password, " \
                      "if an account exists with the email you entered. You should receive them shortly." \
                      "If you don't receive an email, " \
                      "please make sure you've entered the address you registered with, and check your spam folder."
    success_url = reverse_lazy('password_reset_done')

    def get_success_url(self):
        messages.success(self.request, 'Your request to change your password has been registered. Please check your email.')
        return super(ResetPasswordView, self).get_success_url()


class ResetPasswordConfirmView(PasswordResetConfirmView):
    template_name='password_reset_confirm.html',   # type: ignore
    form_class=CustomSetPasswordForm,  # type: ignore
    success_url = reverse_lazy('password_reset_complete')

    def get_success_url(self):
        messages.success(self.request, 'Your password has been successfully changed!')
        return super(ResetPasswordConfirmView, self).get_success_url()


       

def activate(request,uidb64,token):
    uid = force_str(urlsafe_base64_decode(uidb64))
    user = User.objects.filter(pk=uid, is_active = False).first()

    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()
        return redirect("login")
    else:
        return redirect("/")


def account_informatin(request):  # sourcery skip: instance-method-first-arg-name
    if request.method=="POST":
        form=Account_InformationForm(request.POST)
        if form.is_valid(): 
            form.save()
    else:
        form= Account_InformationForm()
    context = {
        'form' : form
    }
    return render(request,'account_information.html', context)


def address_book(request):
    
    return render(request,'address_book.html')


def change_password(request):
    return render(request,'change_password.html')


def login_view(request):
    if request.method=="POST":
        form = LoginForm(request.POST)
        if form.is_valid():
            user=authenticate(request, username = form.cleaned_data['username'], password = form.cleaned_data['password'])
            # login(request, user, backend='django.contrib.auth.backends.ModelBackend')
            if user is not None:
                login(request, user)
                return redirect('index')
            
    else:
        form = LoginForm()

    context ={
        "form": form
    }

    return render(request, 'login.html', context)
   
def register(request):   #sourcery skip: last-if-guard
    if request.method=="POST":
        form=UserRegisterForm(request.POST)
        if form.is_valid():
            form.save()

    else:
        form=UserRegisterForm()
    context={
        "form" : form   
         }
    return render(request,'register.html',context)

user/templates/confirmation_email.html
{% autoescape off %}
Hello, {{ user.get_full_name }},

Please, confirm your registration by clicking the following address:

http://{{ domain }}{% url 'confirmation' uidb64=uid token=token %}

{% endautoescape %}

user/templates/password_reset.html
{% extends 'base.html' %}
{% load static %}
<!-- Favicons Icon -->

<title>Superb premium HTML5 &amp; CSS3 template</title>

<!-- CSS Style -->
{% block css %}
<link rel="stylesheet" type="text/css" href="{% static 'css/internal.css' %}">
{% endblock %}

<html>
<body>
{% block content %}
    <div class="form-content my-3 p-3">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-5">
                    <div class="card shadow-lg border-0 rounded-lg mt-0 mb-3">
                        <div class="card-header justify-content-center">
                            <div id="error_div"></div>
                          <h3 class="font-weight-light my-4 text-center">Forgot Password?</h3>
                          <br>
                        </div>
                        
                        {% if form.errors %}

                            <div class="alert alert-danger alert-dismissible" role="alert">
                                    {% for key, value in form.errors.items %}
                                        <strong>{{ value }}</strong>
                                    {% endfor %}
                                </div>
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                        {% endif %}
                        <div class="card-body">
                            <form method="POST">
                                {% csrf_token %}
                                <div class="form-row">
                                    <div class="col-md-10 offset-md-1">
                                    <div class="form-group">
                                        <strong>Retrieve your password here.</strong>
                                        <div class="content">
                                          <p>Please enter your email address below. You will receive a link to reset your password.</p>
                                      <label class="small mb-1" for="id_email">Email</label>
                                        <input type="email" name="email"  class="form-control"
                                               autocomplete="email" maxlength="254" required id="id_email"
                                               placeholder="Enter email">
                                    </div>
                                </div>
                            </div>
                                <div class="form-row">
                                  <div class="col-md-10 offset-md-1">
                                    <div class="form-group mt-0 mb-1">
                                        <button type="submit" class="col-md-12 btn btn-dark">Submit
                                        </button>
                                    </div>
                                    <div class="card-footer text-center">
                                        <div class="small">
                                            <br>
                                            <br>
                                            <a href="{% url 'register' %}">Create A New Account</a> 
                                            <br> 
                                            <a href="{% url 'login' %}">Back To Login</a><br>
                                        </div>
                                    </div>
                                 </div>
                               </div>
                            </form>
                        </div>
                       
                        </div>
                    </div>
                </div>
            </div>
        </div>

  </div>



  <!-- Brand logo starts  -->
  <div class="brand-logo wow bounceInUp animated">
    <div class="container">
      <div class="slider-items-products">
        <div id="brand-logo-slider" class="product-flexslider hidden-buttons">
          <div class="slider-items slider-width-col6"> 
            
            
            <!-- Item -->
            <div class="item"><a href="#"><img src="{% static 'images/b-logo3.png' %}" alt="Image"></a> </div>
            <!-- End Item --> 
            
            <!-- Item -->
            <div class="item"><a href="#"><img src="{% static 'images/b-logo2.png' %}" alt="Image"></a> </div>
            <!-- End Item --> 
            
            <!-- Item -->
            <div class="item"><a href="#"><img src="{% static 'images/b-logo1.png' %}" alt="Image"></a> </div>
            <!-- End Item --> 
            
            <!-- Item -->
            <div class="item"><a href="#"><img src="{% static 'images/b-logo4.png' %}" alt="Image"></a> </div>
            <!-- End Item --> 
            
            <!-- Item -->
            <div class="item"><a href="#"><img src="{% static 'images/b-logo5.png' %}" alt="Image"></a> </div>
            <!-- End Item --> 
            
            <!-- Item -->
            <div class="item"><a href="#"><img src="{% static 'images/b-logo6.png' %}" alt="Image"></a> </div>
            <!-- End Item --> 
            
            <!-- Item -->
            <div class="item"><a href="#"><img src="{% static 'images/b-logo1.png' %}" alt="Image"></a> </div>
            <!-- End Item --> 
            
            
          </div>
        </div>
      </div>
    </div>
  </div>
  <!-- Brand logo ends  --> 
  

</div>

{% endblock content %}
<!-- JavaScript -->
{% block js%}  
<script type="text/javascript" src="{% static 'js/parallax.js' %}"></script>
<script type="text/javascript" src="{% static 'js/jquery.flexslider.js' %}"></script>
<script type="text/javascript" src="{% static 'js/cloud-zoom.js' %}"></script>
{% endblock %}
</body>
</html>

user/templates/password_reset_confirm.html
{% extends "base.html" %}
{% load static %}

{% block icon %} {% endblock %}
{% block title %}
<title>Superb premium HTML5 &amp; CSS3 template</title>
{% endblock %}

{% block css %}
<!-- CSS Style -->
<link rel="stylesheet" type="text/css" href="{% static 'css/internal.css' %}">

{% endblock %}

<html>
<body>

{% block content %}
    <div class="form-content my-3 p-3">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-5">
                    {% if validlink %}
                        <div class="card shadow-lg border-0 rounded-lg mt-0 mb-3">
                            <div class="card-header justify-content-center">
                              <h3 class="font-weight-light my-4 text-center">Reset Your Password</h3>
                            </div>
                            {% if form.errors %}
                                <div class="alert alert-danger alert-dismissible" role="alert">
                                    <div id="form_errors">
                                        {% for key, value in form.errors.items %}
                                            <strong>{{ value }}</strong>
                                        {% endfor %}
                                    </div>
                                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                            {% endif %}

                            <div class="card-body">
                                <form method="POST">
                                    {% csrf_token %}
                                    <div class="form-row">
                                        <div class="col-md-10 offset-md-1">
                                            <div class="form-group">
                                                <label class="small mb-1" for="id_new_password1">New Password</label>
                                                <input type="password" name="new_password1" autocomplete="new-password"
                                                       class="form-control" required id="id_new_password1"
                                                       placeholder="Enter password"/>
                                                <span>
                                                </span>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="form-row">
                                        <div class="col-md-10 offset-md-1">
                                            <div class="form-group">
                                                <label class="small mb-1" for="id_new_password2">New Password Confirmation</label>
                                                <input type="password" name="new_password2" autocomplete="new-password"
                                                       required id="id_new_password2" class="form-control"
                                                       placeholder="Confirm password"/>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="form-row">
                                        <div class="col-md-10 offset-md-1">
                                            <div class="form-group mt-0 mb-1">
                                                <button type="submit" class="col-md-12 btn btn-dark" id="reset">Reset Password</button>
                                            </div>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                    {% else %}
                    <div class="alert alert-warning">
                        The password reset link was invalid, possibly because it has already been used.
                        Please request a new password reset.
                    </div>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>


  <!-- Brand logo starts  -->
  <div class="brand-logo wow bounceInUp animated">
    <div class="container">
      <div class="slider-items-products">
        <div id="brand-logo-slider" class="product-flexslider hidden-buttons">
          <div class="slider-items slider-width-col6"> 
            
          
            <!-- Item -->
            <div class="item"><a href="#"><img src="{% static 'images/b-logo3.png' %}" alt="Image"></a> </div>
            <!-- End Item --> 
            
            <!-- Item -->
            <div class="item"><a href="#"><img src="{% static 'images/b-logo2.png' %}" alt="Image"></a> </div>
            <!-- End Item --> 
            
            <!-- Item -->
            <div class="item"><a href="#"><img src="{% static 'images/b-logo1.png' %}" alt="Image"></a> </div>
            <!-- End Item --> 
            
            <!-- Item -->
            <div class="item"><a href="#"><img src="{% static 'images/b-logo4.png' %}" alt="Image"></a> </div>
            <!-- End Item --> 
            
            <!-- Item -->
            <div class="item"><a href="#"><img src="{% static 'images/b-logo5.png' %}" alt="Image"></a> </div>
            <!-- End Item --> 
            
            <!-- Item -->
            <div class="item"><a href="#"><img src="{% static 'images/b-logo6.png' %}" alt="Image"></a> </div>
            <!-- End Item --> 
            
            <!-- Item -->
            <div class="item"><a href="#"><img src="{% static 'images/b-logo1.png' %}" alt="Image"></a> </div>
            <!-- End Item --> 
            
            <!-- Item -->
            <div class="item"><a href="#"><img src="{% static 'images/b-logo4.png' %}" alt="Image"></a> </div>
            <!-- End Item --> 
            
            
            <!-- Item -->
            <div class="item"><a href="#"><img src="{% static 'images/b-logo4.png' %}" alt="Image"></a> </div>
            <!-- End Item --> 
            
          </div>
        </div>
      </div>
    </div>
  </div>
  <!-- Brand logo ends  --> 
  
 </div>
<br>

{% endblock content %}

{% block js %}
<!-- JavaScript --> 
<script type="text/javascript" src="{% static 'js/parallax.js' %}"></script>
<script type="text/javascript" src="{% static 'js/jquery.flexslider.js' %}"></script>
<script type="text/javascript" src="{% static 'js/cloud-zoom.js' %}"></script>
{% endblock %}
</body>
</html>

{% comment %} {% block content %}

  {% load crispy_forms_tags %}  
  
  <!--Password Reset Confirm-->
    <div class="container p-5">
	    <h2 class="font-weight-bold mt-3">Password Reset Confirm</h2>
		<hr>
        <p>Please enter your new password.</p>
        <form method="POST">
            {% csrf_token %}
            {{ form|crispy }}                    
            <button class="btn btn-primary" type="submit">Reset password</button>
        </form>
    </div>

{% endblock %} {% endcomment %}

user/templates/password_reset_email.html
{% comment %} {% load i18n %}{% autoescape off %}
{% blocktrans %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktrans %}

{% trans "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'accounts:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% trans "Your login email, in case you've forgotten, is same this email address:" %} {{ user.get_username }}

{% trans "Thanks for using our site!" %}

{% blocktrans %}The {{ site_name }} team{% endblocktrans %}

{% endautoescape %} {% endcomment %}

{% autoescape off %}
  To initiate the password reset process for your {{ user.email }} Django Registration/Login App Account,
  click the link below:

  {{ protocol }}://{{ domain }}{% url 'password_reset_confirm' uidb64=uid token=token %}

  If clicking the link above doesn't work, please copy and paste the URL in a new browser
  window instead.

  Sincerely,
  The Developer
{% endautoescape %}